/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CameraJNI */

#ifndef _Included_CameraJNI
#define _Included_CameraJNI
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
