/* DO NOT EDIT THIS FILE - it is machine generated */
#include <C:\Program Files\Java\jdk1.8.0_31\include\jni.h>
/* Header for class CameraJNI */

#ifndef _Included_CameraJNI
#define _Included_CameraJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CameraJNI
 * Method:    GetArrayFromC
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_CameraJNI_GetArrayFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
