/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GibbotVision */

#ifndef _Included_GibbotVision
#define _Included_GibbotVision
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GibbotVision
 * Method:    startCameras
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_GibbotVision_startCameras
  (JNIEnv *, jobject);

/*
 * Class:     GibbotVision
 * Method:    stopCameras
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_GibbotVision_stopCameras
  (JNIEnv *, jobject);

/*
 * Class:     GibbotVision
 * Method:    getGibbotData
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_GibbotVision_getGibbotData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
